[default]
solc_version = '0.7.6'
optimizer_runs = 99999

[core]
src = 'packages/contracts-core/contracts'
out = 'packages/contracts-core/foundry_artifacts'
optimizer_runs = 99999

[router]
src = 'packages/contracts-router/contracts'
out = 'packages/contracts-router/foundry_artifacts'
optimizer_runs = 99999

[bridge]
src = 'packages/contracts-bridge/contracts'
out = 'packages/contracts-bridge/foundry_artifacts'
optimizer_runs = 99999