name: Build and Test Packages
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - run: |
          yarn install --immutable-cache
      - run: |
          yarn lint
      - name: Get latest accumulator-cli version
        id: acli-version
        run: |
          echo "::set-output name=ACLI_HASH::$(curl https://api.github.com/repos/odyslam/accumulator-cli/git/refs/heads/master | jq '.object.sha' -r)"
      - name: Accumulator-cli Cache
        id: cache-acli
        uses: actions/cache@v3
        with:
          path: scripts/accumulator-cli
          key: ${{ runner.os }}-${{ steps.acli-version.outputs.ACLI_HASH }}-accumulator-cli
      - uses: actions-rs/toolchain@v1
        if: steps.cache-acli.outputs.cache-hit != 'true'
        with:
          profile: minimal
          toolchain: stable
      - run: |
          yarn build:accumulator-cli
      - name: Cache contracts-core
        id: cache-contracts-core
        uses: actions/cache@v3
        with:
          path: |
            packages/contracts-core/src
            packages/contracts-core/cache
            packages/contracts-core/artifacts
          key: ${{ hashFiles(packages/contracts-core/contracts/*) }}
      - name: Cache contracts-bridge
        id: cache-contracts-bridge
        uses: actions/cache@v3
        with:
          path: |
            packages/contracts-bridge/src
            packages/contracts-bridge/cache
            packages/contracts-bridge/artifacts
          key: ${{ hashFiles(packages/contracts-bridge/contracts/*) }}
      - name: Cache contracts-router
        id: cache-contracts-router
        uses: actions/cache@v3
        with:
          path: |
            packages/contracts-router/src
            packages/contracts-router/cache
            packages/contracts-router/artifacts
          key: ${{ hashFiles(packages/contracts-router/contracts/*) }}
      - run: |
          yarn build
      - run: |
          yarn test
      - name: "Check Gas snapshot"
        continue-on-error: true
        id: snapshot-check
        run: |
          yarn snapshot:check
